# Generated by Django 4.2 on 2024-07-02 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, null=True)),
                ('date_dispatch', models.DateField()),
                ('date_receipt', models.DateField()),
                ('description', models.CharField(blank=True, null=True)),
                ('attachments', models.FileField(upload_to='attachments/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_messages', to='users.user')),
            ],
        ),
    ]
