# Generated by Django 4.2 on 2024-07-03 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_messages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='attachments',
            field=models.FileField(blank=True, null=True, upload_to='attachments/'),
        ),
    ]
